SELECT
  PRODUCT_NAME,
  AVG(SALES_PRICE)
FROM
  IPHONE_DATA
GROUP BY PRODUCT_NAME

SELECT 
    PRODUCT_NAME,
    SALES_PRICE,
    STAR_RATING
FROM IPHONE_DATA
WHERE STAR_RATING > 4 AND SALES_PRICE BETWEEN 60000 AND 100000